version: '3.8'

services:
  # BG Ingest API Service - Standalone Development
  bg-ingest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - dynamodb-local
      - rabbitmq
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SERVICE_ENV=development
      - LOG_LEVEL=DEBUG
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001
    networks:
      - bg-ingest-network

  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - bg-ingest-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - bg-ingest-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # DynamoDB Admin UI (Optional - helpful for development)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local
    networks:
      - bg-ingest-network

networks:
  bg-ingest-network:
    driver: bridge

volumes:
  dynamodb-data:
  rabbitmq-data: 
