name: BG Ingest Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/services/bg-ingest/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'projects/services/bg-ingest/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/services/bg-ingest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      run: |
        poetry install
        
    - name: Lint with flake8
      run: |
        poetry run flake8 src tests
        
    - name: Type check with mypy
      run: |
        poetry run mypy src tests
        
    - name: Format check with black
      run: |
        poetry run black --check src tests
        
    - name: Test with pytest
      run: |
        poetry run pytest
        
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: projects/services/bg-ingest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: bg-ingest
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 